site_name: Documentation
site_url: https://CanelaSoftware.github.io/Quizli_Documentation
repo_url: https://github.com/CanelaSoftware/Quizli_Documentation
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: light green
    accent: light green
  logo: assets/Quizli Logo (White).svg
  favicon: assets/Quizli Logo (White).svg
  features:
    - content.action.edit
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition

nav:
  - Home: index.md
  - Teachers:
      - Running a Quiz: teachers/running-a-quiz.md
      - Creating a Quiz: teachers/creating-a-quiz.md
      - Creating a Quiz with AI: teachers/creating-a-quiz-with-ai.md
  - Students:
      - Taking a Quiz: students/taking-a-quiz.md

copyright: Copyright &copy; 2024 — 2025 Canela Software
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/27A3eTAG
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/canela-software-inc/
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/appli-io.bsky.social
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
